accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import logged_out_view  
from clients.views import tenant_expire_check


from django.views.generic import TemplateView
from.forms import PwdResetConfirmForm,PwdResetForm



app_name = 'accounts'

urlpatterns = [
    path('', tenant_expire_check, name='tenant_expire_check'),
    path('home/', views.home, name='home'),

    path('login/', views.login_view, name='login'),
    path('login_public/', views.login_public, name='login_public'),   
    path('login_partner_job_seeker/', views.login_partner_job_seeker, name='login_partner_job_seeker'),
    
    #path('logout/', auth_views.LogoutView.as_view(next_page='accounts:logged_out'), name='logout'),
    path('logout/', views.logged_out_view, name='logout'),
 
   
   ###################################################################################################
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_reset/password_change.html',
            success_url='/password_change/done/'), name='password_change' ),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_reset/password_change_done.html', ),
          name='password_change_done'),
    ################################################################################

      # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="accounts/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
          ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
         ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="accounts/password_reset/reset_status.html"),
        name="password_reset_done",
          ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="accounts/password_reset/reset_status.html"),
        name="password_reset_complete",
          ),

   ####################################################################################################
  
   # Custom views
    path('register/', views.register_view, name='register'), 
    path('register_partner_job_seeker/', views.register_partner_job_seeker, name='register_partner_job_seeker'),
    # path('register_job_seeker/', views.register_job_seeker, name='register_job_seeker'), 
    path('register_public/', views.register_public, name='register_public'),   
    path("activate/<slug:uidb64>/<slug:token>)/", views.account_activate, name="activate"),
  
    path('update_profile_picture/', views.update_profile_picture, name='update_profile_picture'),
    path('common_search/', views.common_search, name='common_search'),

    ###################################################################################################
  # Permission
  path('assign_permissions/', views.assign_permissions, name='assign_permissions'),
  path('assign_user_to_group/', views.assign_user_to_group, name='assign_user_to_group'),
  path('assign_permissions_to_group/', views.assign_permissions_to_group, name='assign_permissions_to_group'),
  path('get_permissions_for_model/', views.get_permissions_for_model, name='get_permissions_for_model'),
  path('search_all/', views.search_all, name='search_all')
  

]

core/urls.py
from django.urls import path
from .import views


app_name = 'core'


urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.dashboard, name='dashboard'),
    path('core_dashboard/', views.core_dashboard, name='core_dashboard'),
    path('only_core_dashboard/', views.only_core_dashboard, name='only_core_dashboard'),
    path('view_employee/', views.view_employee, name='view_employee'),
    path('employee_list/', views.employee_list, name='employee_list'),
   
    path('manage_department/', views.manage_department, name='manage_department'),  
    path('manage_location/', views.manage_location, name='manage_location'),

    path('create_positionn/', views.manage_position, name='create_position'),    
    path('update_positionn/<int:id>/', views.manage_position, name='update_position'),    
    path('delete_position/<int:id>/', views.delete_position, name='delete_position'),  
    path('position_details/<int:id>/', views.position_details, name='position_details'),  

    path('create_job_requirement/', views.manage_job_requirement, name='create_job_requirement'),    
    path('update_job_requirement/<int:id>/', views.manage_job_requirement, name='update_job_requirement'),    
    path('delete_job_requirement/<int:id>/', views.delete_job_requirement, name='delete_job_requirement'),  

    path('create_job_description/', views.manage_job_description, name='create_job_description'),    
    path('update_job_description/<int:id>/', views.manage_job_description, name='update_job_description'),    
    path('delete_job_description/<int:id>/', views.delete_job_descriptiont, name='delete_job_description'),  

    path('create_company/', views.create_company, name='create_company'),
    path('update_company/<int:id>/', views.create_company, name='update_company'),
    path('delete_company/<int:id>/', views.delete_company,  name='delete_company'),    
    
    path('manage_employee/', views.manage_employee, name='manage_employee'),
    path('update_employee/<int:id>/', views.manage_employee, name='update_employee'),
    path('delete_employee/<int:id>/', views.delete_employee,  name='delete_employee'),    
            
    path('add_notice/', views.add_notice, name='add_notice'), 
    path('view_notices/', views.view_notices, name='view_notices'),  
    path('all_qc/', views.all_qc, name='all_qc'),

    path('view_attendance/', views.view_attendance, name='view_attendance'),
    path('attendance_input/', views.attendance_input, name='attendance_input'),
    path('update_attendance/<int:employee_id>/', views.update_attendance, name='update_attendance'),     
    
    path('create_salary/', views.create_salary, name='create_salary'),
    path('download_salary/', views.download_salary, name='download_salary'),

    path('view_employee_changes/', views.view_employee_changes, name='view_employee_changes'),
    path('download_employee_changes/', views.download_employee_changes, name='download_employee_changes'),

    path('view_employee_changes_single/<int:employee_id>/', views.view_employee_changes_single, name='view_employee_changes_single'),
    
    path('preview_pay_slip/<int:employee_id>/', views.preview_pay_slip, name='preview_pay_slip'),
    path('generate_and_send_pay_slip/<int:employee_id>/', views.generate_and_send_pay_slip, name='generate_and_send_pay_slip'),
        
    path('preview_salary_certificate/<int:employee_id>/', views.preview_salary_certificate, name='preview_salary_certificate'),
    path('generate_and_send_salary_certificate/<int:employee_id>/', views.generate_and_send_salary_certificate, name='generate_and_send_salary_certificate'),
          
    path('preview_experience_certificate/<int:employee_id>/', views.preview_experience_certificate, name='preview_experience_certificate'),
    path('generate_and_send_experience_certificate/<int:employee_id>/', views.generate_and_send_experience_certificate, name='generate_and_send_experience_certificate'),
      
    path('create_company_policy/', views.manage_company_policy, name='create_company_policy'),
    path('update_company_policy/<int:id>/', views.manage_company_policy, name='update_company_policy'),
    path('delete_company_policy/<int:id>/', views.delete_company_policy, name='delete_company_policy'),   

    path('create_salary_structure/', views.manage_salary_structure, name='create_salary_structure'),
    path('update_salary_structure/<int:id>/', views.manage_salary_structure, name='update_salary_structure'),
    path('delete_salary_structure/<int:id>/', views.delete_salary_structure, name='delete_salary_structure'),   
    
    path('create_festival/', views.manage_festival, name='create_festival'),
    path('update_festival/<int:id>/', views.manage_festival, name='update_festival'),
    path('delete_festival/<int:id>/', views.delete_festival, name='delete_festival'),   

    path('create_performance_bonus/', views.manage_performance_bonus, name='create_performance_bonus'),
    path('update_performance_bonus/<int:id>/', views.manage_performance_bonus, name='update_performance_bonus'),
    path('delete_performance_bonus/<int:id>/', views.delete_performance_bonus, name='delete_performance_bonus'),   

    path('create_leave_type/', views.manage_leave_type, name='create_leave_type'),
    path('update_leave_type/<int:id>/', views.manage_leave_type, name='update_leave_type'),
    path('delete_leave_type/<int:id>/', views.delete_leave_type, name='delete_leave_type'), 

    path('apply_leave/', views.apply_leave, name='apply_leave'),
    path('leave_history/', views.leave_history, name='leave_history'),
    path('pending_leave_list/', views.pending_leave_list, name='pending_leave_list'),
    path('approve_leave/<int:leave_id>/', views.approve_leave, name='approve_leave'),  
    path('leave_summary/', views.leave_summary, name='leave_summary'),
    path('leave_dashboard/', views.leave_dashboard, name='leave_dashboard'),

    path('carry-forward-leave/', views.carry_forward_leave, name='carry_forward_leave'),
    path('update_leave_balances_for_all/', views.monthly_leave_accrual_update, name='update_leave_balances_for_all'),
    path('check_and_deduct_late_leaves/', views.check_and_deduct_late_leaves, name='check_and_deduct_late_leaves'),

]

dscm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path("accounts/", include("django.contrib.auth.urls")), 

    path('core/',include('core.urls',namespace='core')),
    path('clients/',include('clients.urls',namespace='clients')),

    path('logistics/',include('logistics.urls',namespace='logistics')),
    path('manufacture/',include('manufacture.urls',namespace='manufacture')),
    path('product/',include('product.urls',namespace='product')),
    path('purchase/',include('purchase.urls',namespace='purchase')),
    path('sales/',include('sales.urls',namespace='sales')),
    path('supplier/',include('supplier.urls',namespace='supplier')),
    path('inventory/',include('inventory.urls',namespace='inventory')),
    path('finance/',include('finance.urls',namespace='finance')),
    path('shipment/',include('shipment.urls',namespace='shipment')),
    path('reporting/',include('reporting.urls',namespace='reporting')),
    path('customer/',include('customer.urls',namespace='customer')),
    path('repairreturn/',include('repairreturn.urls',namespace='repairreturn')),
    path('operations/',include('operations.urls',namespace='operations')),
    path('tasks/',include('tasks.urls',namespace='tasks')),
    path('commonapp/',include('commonapp.urls',namespace='commonapp')),
    path('transport/',include('transport.urls',namespace='transport')),
    path('customerportal/',include('customerportal.urls',namespace='customerportal')),
    path('recruitment/',include('recruitment.urls',namespace='recruitment')),
   
   
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

operations/urls.py
from django.urls import path
from .import views


app_name = 'operations'


urlpatterns = [   

  path('operations_dashboard/', views.operations_dashboard, name='operations_dashboard'),
 
  path('add_existing_items/', views.add_existing_items, name='add_existing_items'),
  path('confirm_add_existing_items/', views.confirm_add_existing_items, name='confirm_add_existing_items'),
  path('existing_items_list/', views.existing_items_list, name='existing_items_list'),

  path('create_operations_items_request', views.create_operations_items_request, name='create_operations_items_request'),
  path('confirm_operations_items_request/', views.confirm_operations_items_request, name='confirm_operations_items_request'), 
  path('operations_request_order_list/', views.operation_request_order_list, name='operations_request_order_list'),
  path('operations_request_order_items<int:order_id>//', views.operation_request_order_items, name='operations_request_order_items'),

  path('create_operations_items_delivery/<int:request_id>/', views.create_operations_items_delivery, name='create_operations_items_delivery'),
  path('confirm_operations_items_delivery/', views.confirm_operations_items_delivery, name='confirm_operations_items_delivery'),
]

templates/operations/confirm_add_existing_items.html
{% extends "base.html" %}

{% block content %}


<div class="container-fluid main-content">
    <div class="row">        
        <div class="col-12">

            {% if basket %}
            <table class="table table-hover">
                <thead class="table-dark">                       
                    <h4>Items requested</h4>
                        <tr>
                            <th>Product</th>
                            <th>Category</th>                            
                            <th style="white-space: nowrap;">Quantity</th>
                            <th style="white-space: nowrap;" >Unit Price</th>                       
                            <th>Change</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in basket %}
                        <tr>
                            <td style="white-space: nowrap;">{{ item.name }}</td>  
                            <td style="white-space: nowrap;">{{ item.category }}</td>                          
                           
                            <td style="white-space: nowrap;">{{ item.quantity }}</td>
                            <td style="white-space: nowrap;">{{ item.unit_price }}</td>
                        
                            <td style="white-space: nowrap;">
                                <form method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ item.id }}">
                                    <input type="number" name="quantity" value="{{ item.quantity }}" min="1" class="form-control d-inline w-25">
                                    <button type="submit" name="action" value="update" class="btn btn-sm btn-warning">Update</button>
                                </form>
                                <form method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ item.id }}">                                  
                                    <button type="submit" name="action" value="delete" class="btn btn-sm btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" name="confirm_purchase" class="btn btn-success">Confirm Purchase</button>
                </form>
            {% else %}
                <p>No products added to the list yet.</p>
            {% endif %}
        </div>

    </div>
</div>




{% endblock %}

templates/operations/confirm_operations_items_delivery.html
{% extends 'base.html' %}

{% block content %}



<div class="container main-content">
    <h4 class="text-center">Confirm Delivery Order</h4>

    <h4>Items to be delivered</h4>
    {% if basket %}
    <table class="table table-hover">
        <thead class="table-dark">
            <tr class="bg-primary text-white">
                <th>Product</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Warehouse</th>
                <th>Location</th>             
            </tr>
        </thead>
        <tbody>
            {% for item in basket %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.category }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.warehouse_name }}</td>
                <td>{{ item.location_name }}</td>              
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Confirm Delivery Order</button>
    </form>
    {% else %}
    <p>No items in the basket to confirm.</p>
    {% endif %}
</div>




{% endblock %}

templates/operations/create_add_existing_items.html
{% extends "base.html" %}

{% block content %}





<div class="container-fluid main-content">
    <div class="row">
        <div class="col-12 col-md-3">
            <div class="card shadow-lg" style="background-color: aliceblue;">
                <!-- Card Header -->
                <div class="card-header bg-primary text-white text-center">
                    <h4 class="mb-0">Add existing items</h4>
                </div> 
                <div class="card-body">                   
                    <form method="post" enctype="multipart/form-data" action="{% url 'operations:add_existing_items' %}" id="add_category">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid">
                        <button type="submit" name="add_to_basket" class="btn btn-primary btn-lg">Add to list</button>
                    </div>
                    </form>
                 </div>
            </div>           
        </div>
        <div class="col-12 col-md-9">

            {% if basket %}
            <table class="table table-hover">
                <thead class="table-dark">                      
                    <h4>Items to be added</h4>
                        <tr>
                            <th>Product</th>
                            <th>Category</th>                            
                            <th style="white-space: nowrap;">Quantity</th>
                            <th style="white-space: nowrap;" >Unit Price</th>                       
                            <th>Change</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in basket %}
                        <tr>
                            <td style="white-space: nowrap;">{{ item.name }}</td>  
                            <td style="white-space: nowrap;">{{ item.category }}</td>                          
                           
                            <td style="white-space: nowrap;">{{ item.quantity }}</td>
                            <td style="white-space: nowrap;">{{ item.unit_price }}</td>
                        
                            <td style="white-space: nowrap;">
                                <form method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ item.id }}">
                                    <input type="number" name="quantity" value="{{ item.quantity }}" min="1" class="form-control d-inline w-25">
                                    <button type="submit" name="action" value="update" class="btn btn-sm btn-warning">Update</button>
                                </form>
                                <form method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ item.id }}">                                  
                                    <button type="submit" name="action" value="delete" class="btn btn-sm btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" name="confirm_purchase" class="btn btn-success">Confirm Purchase</button>
                </form>
            {% else %}
                <p>No products added to the list yet.</p>
            {% endif %}
        </div>

    </div>
</div>




{% endblock %}

templates/operations/create_operations_items_request.html
{% extends "base.html" %}

{% block content %}




<div class="container-fluid main-content">
    <div class="row">
        <div class="col-12 col-md-3">
            <div class="card shadow-lg" style="background-color: aliceblue;">
                <!-- Card Header -->
                <div class="card-header bg-primary text-white text-center">
                    <h5 class="mb-0">Create Materials request</h5>
                </div> 
                <div class="card-body">                   
                    <form method="post" enctype="multipart/form-data" action="{% url 'operations:create_operations_items_request' %}" id="add_category">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid">
                        <button type="submit" name="add_to_basket" class="btn btn-primary btn-lg">Add to list</button>
                    </div>
                    </form>
                 </div>
            </div>           
        </div>
        <div class="col-12 col-md-9">

            {% if basket %}
            <table class="table table-hover">
                <thead class="table-dark">                      
                    <h4>Items requested</h4>
                        <tr class="bg-primary text-white">
                            <th>Product</th>
                            <th>Category</th>                            
                            <th style="white-space: nowrap;">Quantity</th>
                            <th style="white-space: nowrap;" >Unit Price</th>                       
                            <th>Change</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in basket %}
                        <tr>
                            <td style="white-space: nowrap;">{{ item.name }}</td>  
                            <td style="white-space: nowrap;">{{ item.category }}</td>                          
                           
                            <td style="white-space: nowrap;">{{ item.quantity }}</td>
                            <td style="white-space: nowrap;">{{ item.unit_price }}</td>
                        
                            <td style="white-space: nowrap;">
                                <form method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ item.id }}">
                                    <input type="number" name="quantity" value="{{ item.quantity }}" min="1" class="form-control d-inline w-25">
                                    <button type="submit" name="action" value="update" class="btn btn-sm btn-warning">Update</button>
                                </form>
                                <form method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ item.id }}">                                  
                                    <button type="submit" name="action" value="delete" class="btn btn-sm btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" name="confirm_purchase" class="btn btn-success">Confirm request</button>
                </form>
            {% else %}
                <p>No products added to the list yet.</p>
            {% endif %}
        </div>

    </div>
</div>



{% endblock %}

templates/operations/operations_dashboard.html
{% extends 'base.html' %}  

{% block content %}


    


<div class="container-fluid main-content">
    <div class="row">     

        <div class="col-6 col-md-3 col-lg-2 p-2">
            <a href="{% url 'operations:add_existing_items' %}" class="text-decoration-none">
                <div class="menu-card">
                    <i class="fas fa-plus-square menu-icon"></i>
                    <div class="menu-title">Add existing item</div>
                </div>
            </a>
        </div>      

        <div class="col-6 col-md-3 col-lg-2 p-2">
            <a href="{% url 'operations:existing_items_list' %}" class="text-decoration-none">
                <div class="menu-card">
                    <i class="fas fa-list menu-icon"></i>
                    <div class="menu-title">Existing item  List</div>
                </div>
            </a>
        </div>  
        <div class="col-6 col-md-3 col-lg-2 p-2">
            <a href="{% url 'operations:create_operations_items_request' %}" class="text-decoration-none">
                <div class="menu-card">
                    <i class="fas fa-plus-square menu-icon"></i>
                    <div class="menu-title">Apply for requiremen</div>
                </div>
            </a>
        </div>  


        <div class="col-6 col-md-3 col-lg-2 p-2">
            <a href="{% url 'operations:operations_request_order_list' %}" class="text-decoration-none">
                <div class="menu-card">
                    <i class="fas fa-plus-square menu-icon"></i>
                    <div class="menu-title">Create delivery</div>
                </div>
            </a>
        </div>  

    </div>
</div>




    {% endblock %}

 

templates/operations/operations_request_order_list.html
{% extends "base.html" %}

{% block content %}


   <div class="container-fluid main-content">
    <div class="row">       

           <div class="col-12">     
            <div class="container">
                <div class="row">
                    <div class="col-7">
                        <form method ="GET" action="">
                            <label for="id_operations_request_order_id"> Request Order id</label>
                             {{ form.operations_request_order_id}}
                            <button type="Submit" class="btn btn-primary">Search</button>                           
                        </form>           
                    </div>
                    <div class="col-5">                  
                        {% if request_order %}
                            Search result for sale order: <b>{{ request_order }}</b>
                            {% else %}
                        <span> ID does not match</span>
                        {% endif %}  
                    
                    </div>
                </div>
            </div>

        </div>      
        <hr class="mt-2">
        <div class="col-12 col-md-12">
          
            <table class="table table-hover">
                <thead class="table-dark">                      
                    <h4>Operations Request Order</h4>
                        <tr>
                            
                            <th>Request Number</th>                            
                            <th style="white-space: nowrap;">Total amount</th>
                            <th style="white-space: nowrap;">Requested items</th>
                            <th style="white-space: nowrap;">Requested by</th>
                            <th style="white-space: nowrap;">Create Delivery</th>
                         
                                              
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in page_obj%}
                        <tr>
                            <td style="white-space: nowrap;">{{ order.order_id }}</td>                             
                            <td style="white-space: nowrap;">{{ order.total_amount }}</td> 
                            <td style="white-space: nowrap;">
                                <a href="{% url 'operations:operations_request_order_items' order.id %}">Requested items</a>
                            </td>  
                            <td style="white-space: nowrap;">{{ order.user}}</td> 
                            <td>
                             <a href="{% url 'operations:create_operations_items_delivery' order.id %}" class="btn btn-sm btn-primary">Create delivery</a></td>                    
                            
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="5" class="text-center">No pending. All requested order delivered</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
         
        </div>
    </div>

    
 <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

</div>


<script>
    $(document).ready(function() {
        $('#id_operations_request_order_id').select2({
            width: '70%',
            placeholder: 'Search order...',
            allowClear: true,
            ajax: {
                url: "{% url 'accounts:common_search' %}",  // Ensure this URL is correct
                dataType: 'json',
                delay: 250,
                data: function(params) {
                    return {
                        q: params.term
                    };
                },
                processResults: function(data) {
                    return {
                        results: $.map(data.results, function(item) {
                            return {
                                id: item.id,
                                text: item.text
                            };
                        })
                    };
                },
                cache: true
            },
            minimumInputLength: 1,
            placeholder: 'Search for order',
            allowClear: true
        });
    });

    </script>
    



{% endblock %}