core/urls.py
from django.urls import path
from .import views


app_name = 'core'


urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.dashboard, name='dashboard'),
    path('core_dashboard/', views.core_dashboard, name='core_dashboard'),
    path('only_core_dashboard/', views.only_core_dashboard, name='only_core_dashboard'),
    path('view_employee/', views.view_employee, name='view_employee'),
    path('employee_list/', views.employee_list, name='employee_list'),
   
    path('manage_department/', views.manage_department, name='manage_department'),  
    path('manage_location/', views.manage_location, name='manage_location'),

    path('create_positionn/', views.manage_position, name='create_position'),    
    path('update_positionn/<int:id>/', views.manage_position, name='update_position'),    
    path('delete_position/<int:id>/', views.delete_position, name='delete_position'),  
    path('position_details/<int:id>/', views.position_details, name='position_details'),  

    path('create_job_requirement/', views.manage_job_requirement, name='create_job_requirement'),    
    path('update_job_requirement/<int:id>/', views.manage_job_requirement, name='update_job_requirement'),    
    path('delete_job_requirement/<int:id>/', views.delete_job_requirement, name='delete_job_requirement'),  

    path('create_job_description/', views.manage_job_description, name='create_job_description'),    
    path('update_job_description/<int:id>/', views.manage_job_description, name='update_job_description'),    
    path('delete_job_description/<int:id>/', views.delete_job_descriptiont, name='delete_job_description'),  

    path('create_company/', views.create_company, name='create_company'),
    path('update_company/<int:id>/', views.create_company, name='update_company'),
    path('delete_company/<int:id>/', views.delete_company,  name='delete_company'),    
    
    path('manage_employee/', views.manage_employee, name='manage_employee'),
    path('update_employee/<int:id>/', views.manage_employee, name='update_employee'),
    path('delete_employee/<int:id>/', views.delete_employee,  name='delete_employee'),    
            
    path('add_notice/', views.add_notice, name='add_notice'), 
    path('view_notices/', views.view_notices, name='view_notices'),  
    path('all_qc/', views.all_qc, name='all_qc'),

    path('view_attendance/', views.view_attendance, name='view_attendance'),
    path('attendance_input/', views.attendance_input, name='attendance_input'),
    path('update_attendance/<int:employee_id>/', views.update_attendance, name='update_attendance'),     
    
    path('create_salary/', views.create_salary, name='create_salary'),
    path('download_salary/', views.download_salary, name='download_salary'),

    path('view_employee_changes/', views.view_employee_changes, name='view_employee_changes'),
    path('download_employee_changes/', views.download_employee_changes, name='download_employee_changes'),

    path('view_employee_changes_single/<int:employee_id>/', views.view_employee_changes_single, name='view_employee_changes_single'),
    
    path('preview_pay_slip/<int:employee_id>/', views.preview_pay_slip, name='preview_pay_slip'),
    path('generate_and_send_pay_slip/<int:employee_id>/', views.generate_and_send_pay_slip, name='generate_and_send_pay_slip'),
        
    path('preview_salary_certificate/<int:employee_id>/', views.preview_salary_certificate, name='preview_salary_certificate'),
    path('generate_and_send_salary_certificate/<int:employee_id>/', views.generate_and_send_salary_certificate, name='generate_and_send_salary_certificate'),
          
    path('preview_experience_certificate/<int:employee_id>/', views.preview_experience_certificate, name='preview_experience_certificate'),
    path('generate_and_send_experience_certificate/<int:employee_id>/', views.generate_and_send_experience_certificate, name='generate_and_send_experience_certificate'),
      
    path('create_company_policy/', views.manage_company_policy, name='create_company_policy'),
    path('update_company_policy/<int:id>/', views.manage_company_policy, name='update_company_policy'),
    path('delete_company_policy/<int:id>/', views.delete_company_policy, name='delete_company_policy'),   

    path('create_salary_structure/', views.manage_salary_structure, name='create_salary_structure'),
    path('update_salary_structure/<int:id>/', views.manage_salary_structure, name='update_salary_structure'),
    path('delete_salary_structure/<int:id>/', views.delete_salary_structure, name='delete_salary_structure'),   
    
    path('create_festival/', views.manage_festival, name='create_festival'),
    path('update_festival/<int:id>/', views.manage_festival, name='update_festival'),
    path('delete_festival/<int:id>/', views.delete_festival, name='delete_festival'),   

    path('create_performance_bonus/', views.manage_performance_bonus, name='create_performance_bonus'),
    path('update_performance_bonus/<int:id>/', views.manage_performance_bonus, name='update_performance_bonus'),
    path('delete_performance_bonus/<int:id>/', views.delete_performance_bonus, name='delete_performance_bonus'),   

    path('create_leave_type/', views.manage_leave_type, name='create_leave_type'),
    path('update_leave_type/<int:id>/', views.manage_leave_type, name='update_leave_type'),
    path('delete_leave_type/<int:id>/', views.delete_leave_type, name='delete_leave_type'), 

    path('apply_leave/', views.apply_leave, name='apply_leave'),
    path('leave_history/', views.leave_history, name='leave_history'),
    path('pending_leave_list/', views.pending_leave_list, name='pending_leave_list'),
    path('approve_leave/<int:leave_id>/', views.approve_leave, name='approve_leave'),  
    path('leave_summary/', views.leave_summary, name='leave_summary'),
    path('leave_dashboard/', views.leave_dashboard, name='leave_dashboard'),

    path('carry-forward-leave/', views.carry_forward_leave, name='carry_forward_leave'),
    path('update_leave_balances_for_all/', views.monthly_leave_accrual_update, name='update_leave_balances_for_all'),
    path('check_and_deduct_late_leaves/', views.check_and_deduct_late_leaves, name='check_and_deduct_late_leaves'),

]

dscm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path("accounts/", include("django.contrib.auth.urls")), 

    path('core/',include('core.urls',namespace='core')),
    path('clients/',include('clients.urls',namespace='clients')),

    path('logistics/',include('logistics.urls',namespace='logistics')),
    path('manufacture/',include('manufacture.urls',namespace='manufacture')),
    path('product/',include('product.urls',namespace='product')),
    path('purchase/',include('purchase.urls',namespace='purchase')),
    path('sales/',include('sales.urls',namespace='sales')),
    path('supplier/',include('supplier.urls',namespace='supplier')),
    path('inventory/',include('inventory.urls',namespace='inventory')),
    path('finance/',include('finance.urls',namespace='finance')),
    path('shipment/',include('shipment.urls',namespace='shipment')),
    path('reporting/',include('reporting.urls',namespace='reporting')),
    path('customer/',include('customer.urls',namespace='customer')),
    path('repairreturn/',include('repairreturn.urls',namespace='repairreturn')),
    path('operations/',include('operations.urls',namespace='operations')),
    path('tasks/',include('tasks.urls',namespace='tasks')),
    path('commonapp/',include('commonapp.urls',namespace='commonapp')),
    path('transport/',include('transport.urls',namespace='transport')),
    path('customerportal/',include('customerportal.urls',namespace='customerportal')),
    path('recruitment/',include('recruitment.urls',namespace='recruitment')),
   
   
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logistics/urls.py
from django.urls import path
from .import views


app_name = 'logistics'


urlpatterns = [
    path('create_purchase_shipment/<int:purchase_order_id>/', views.create_purchase_shipment, name='create_purchase_shipment'),
    path('purchase_shipment_list/', views.purchase_shipment_list, name='purchase_shipment_list'),
    path('purchase_shipment_detail/<int:shipment_id>/', views.purchase_shipment_detail, name='purchase_shipment_detail'),   
    path('create_purchase_dispatch_item/<int:dispatch_id>/', views.create_purchase_dispatch_item, name='create_purchase_dispatch_item'),   
    path('confirm_purchase_dispatch_item/', views.confirm_purchase_dispatch_item, name='confirm_purchase_dispatch_item'),

    path('order/<int:purchase_order_id>/dispatch-items/', views.dispatch_item_list, name='dispatch_item_list'),
    path('dispatch-item/<int:dispatch_item_id>/update-status/', views.update_dispatch_status, name='update_dispatch_status'),
    path('cancel_dispatch_item<int:dispatch_item_id>/', views.cancel_dispatch_item, name='cancel_dispatch_item'),

######################################################################################################
    
    path('create_sale_shipment/<int:sale_order_id>/', views.create_sale_shipment, name='create_sale_shipment'),
    path('sale_shipment_list/', views.sale_shipment_list, name='sale_shipment_list'),
    path('sale_shipment_detail/<int:shipment_id>/', views.sale_shipment_detail, name='sale_shipment_detail'),
    path('create_sale_dispatch_item/<int:dispatch_id>/', views.create_sale_dispatch_item, name='create_sale_dispatch_item'),   
    path('confirm_sale_dispatch_item/', views.confirm_sale_dispatch_item, name='confirm_sale_dispatch_item'),

    path('sale-order/<int:sale_order_id>/dispatch-items/', views.sale_dispatch_item_list, name='sale_dispatch_item_list'),
    path('sale-dispatch-item/<int:dispatch_item_id>/update-status/', views.update_sale_dispatch_status, name='update_sale_dispatch_status'),
   

   path('cancel_sale_dispatch_item/<int:dispatch_item_id>/', views.cancel_sale_dispatch_item, name='cancel_sale_dispatch_item')

    
    
]

sales/urls.py
from django.urls import path
from .import views


app_name = 'sales'


urlpatterns = [    
    
  path('sale_dashboard/', views.sale_dashboard, name='sale_dashboard'),

  path('create_sale_request/', views.create_sale_request, name='create_sale_request'),
  path('cconfirm_sale_request/', views.confirm_sale_request, name='confirm_sale_request'),
  path('process-sale-request/<int:order_id>/', views.process_sale_request, name='process_sale_request'),
  path('sale_request_order_list/', views.sale_request_order_list, name='sale_request_order_list'),   
  path('sale_request_items/<int:order_id>/', views.sale_request_items, name='sale_request_items'),

  path('create_sale_order/<int:request_id>/', views.create_sale_order, name='create_sale_order'),
  path('confirm_sale_order/', views.confirm_sale_order, name='confirm_sale_order'),
  path('process-sale-order/<int:order_id>/', views.process_sale_order, name='process_sale_order'),
  path('sale_order_list/', views.sale_order_list, name='sale_order_list'),
  path('sale_order_list_report/', views.sale_order_list_report, name='sale_order_list_report'),
 

  path('qc_dashboard/', views.qc_dashboard, name='qc_dashboard'),
  path('qc_dashboard/<int:sale_order_id>/', views.qc_dashboard, name='qc_dashboard_with_order'), 
  path('qc_inspect_item/<int:item_id>/', views.qc_inspect_item, name='qc_inspect_item'),


  path('sale_order_item/', views.sale_order_item, name='sale_order_item'),
  path('sale_order_items/<int:order_id>/', views.sale_order_items, name='sale_order_items'),
  path('sale_order_item_dispatch/<str:order_id>/', views.sale_order_item_dispatch, name='sale_order_item_dispatch'),
  path('update_sale_order_status/<int:order_id>/', views.update_sale_order_status, name='update_sale_order_status'),

 path('product_sales_report/', views.product_sales_report, name='product_sales_report'),


]

shipment/urls.py
from django.urls import path
from .import views


app_name = 'shipment'


urlpatterns = [
 path('update_shipment_tracking/<int:shipment_id>/', views.update_shipment_tracking, name='update_shipment_tracking'),
path('update_sale_shipment_tracking/<int:shipment_id>/', views.update_sale_shipment_tracking, name='update_sale_shipment_tracking'),
]

logistics/forms.py
from django import forms
from .models import PurchaseShipment,SaleShipment,PurchaseDispatchItem,SaleDispatchItem
from purchase.models import PurchaseOrderItem
from sales.models import SaleOrder,SaleOrderItem




class PurchaseShipmentForm(forms.ModelForm):
    estimated_delivery = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        required=False
    )
    class Meta:
        model = PurchaseShipment
        fields = ['carrier', 'tracking_number', 'estimated_delivery']




class SaleShipmentForm(forms.ModelForm):
    estimated_delivery = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        required=False
    )
    class Meta:
        model = SaleShipment
        fields = ['carrier', 'tracking_number', 'estimated_delivery','sales_order']

    def __init__(self, *args, sale_order=None, **kwargs):
        super(SaleShipmentForm, self).__init__(*args, **kwargs)
        if sale_order:
            self.fields['sales_order'].queryset = SaleOrder.objects.filter(id=sale_order.id)
        else:
            self.fields['sales_order'].queryset = SaleOrder.objects.all()



class PurchaseDispatchItemForm(forms.ModelForm):
    dispatch_date=forms.DateField(
        widget=forms.DateInput(attrs={'type':'date'}),
        required=False
    )
    delivery_date=forms.DateField(
        widget=forms.DateInput(attrs={'type':'date'}),
        required=False
    )

    class Meta:
        model = PurchaseDispatchItem
        exclude=['dispatch_id','user']


    def __init__(self, *args, purchase_shipment=None, **kwargs):
        super(PurchaseDispatchItemForm, self).__init__(*args, **kwargs)

        if purchase_shipment:
            self.fields['purchase_shipment'].queryset = PurchaseShipment.objects.filter(id=purchase_shipment.id)            
            self.fields['dispatch_item'].queryset = PurchaseOrderItem.objects.filter(purchase_order__purchase_shipment=purchase_shipment)
        else:
            self.fields['purchase_shipment'].queryset = PurchaseShipment.objects.all()
            self.fields['dispatch_item'].queryset = PurchaseOrderItem.objects.all()
         
        self.fields['purchase_shipment'].widget.attrs.update({
            'style': 'max-width: 200px; word-wrap: break-word; overflow: hidden; text-overflow: ellipsis;'
        })
          
        self.fields['dispatch_item'].widget.attrs.update({
            'style': 'max-width: 200px; word-wrap: break-word; overflow: hidden; text-overflow: ellipsis;'
        })

from purchase.models import Batch
from django import forms
from .models import SaleDispatchItem, SaleShipment, SaleOrderItem, Batch

class SaleDispatchItemForm(forms.ModelForm):
    DISPATCH_STRATEGY_CHOICES = [
        ('FIFO', 'First In, First Out'),
        ('LIFO', 'Last In, First Out'),
    ]
    dispatch_strategy = forms.ChoiceField(
        choices=DISPATCH_STRATEGY_CHOICES, 
        required=True,
        widget=forms.Select(attrs={'style': 'max-width: 200px;'})
    )

    class Meta:
        model = SaleDispatchItem
        exclude = ['dispatch_id', 'user']
        widgets = {
            'dispatch_date': forms.DateInput(attrs={'type': 'date'}),
            'delivery_date': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, sale_shipment=None, dispatch_strategy='FIFO', **kwargs):
        super(SaleDispatchItemForm, self).__init__(*args, **kwargs)

        # Set dispatch strategy dynamically
        self.fields['dispatch_strategy'].initial = dispatch_strategy

        if sale_shipment:
            self.fields['sale_shipment'].queryset = SaleShipment.objects.filter(id=sale_shipment.id)
            self.fields['dispatch_item'].queryset = SaleOrderItem.objects.filter(sale_order__sale_shipment=sale_shipment)
            if 'batch' in self.fields:
                self.fields['batch'].queryset = Batch.objects.filter(sale_shipment=sale_shipment)
        else:
            self.fields['sale_shipment'].queryset = SaleShipment.objects.all()
            self.fields['dispatch_item'].queryset = SaleOrderItem.objects.all()
            if 'batch' in self.fields:
                self.fields['batch'].queryset = Batch.objects.all()

        # Styling for dropdowns
        self.fields['sale_shipment'].widget.attrs.update({
            'style': 'max-width: 200px; word-wrap: break-word; overflow: hidden; text-overflow: ellipsis;'
        })
        self.fields['dispatch_item'].widget.attrs.update({
            'style': 'max-width: 200px; word-wrap: break-word; overflow: hidden; text-overflow: ellipsis;'
        })

templates/logistics/sales/cancel_order_item.html
{% extends 'base.html' %}  

{% block content %}





<div class="container-fluid main-content">
    <div class="row"> 
        <div class="col-12 col-md-2"></div>
            <div class="col-12 col-md-8">
                <h4 class="text-center">Are you sure you want to delete ??</h4>       
                <div class="card shadow-lg" style="padding:10px;background-color:azure;">
                    <div class="card-body">
                        <h4>Confirm Deletion</h4>
                            <p>Are you sure you want to delete</p>

                            <form method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">Confirm Delete</button>
                            </form>
                            <a href="{% url 'logistics:sale_dispatch_item_list' dispatch_item.dispatch_item.sale_order.id %}" class="btn btn-secondary m-1">Cancel</a>


                            <!-- <a href="{% url 'sales:sale_order_list' %}" class="btn btn-secondary m-1">Cancel</a> -->

                     </div>
                </div>           
            </div>
            <div class="col-12 col-md-2"></div>
    </div>
</div>



 {% endblock %}

templates/logistics/sales/create_shipment.html
{% extends 'base.html' %}  

{% block content %}



<div class="container-fluid main-content">
    <div class="row">
        <div class="col-12">
            <h4>Create Shipment for {{ sale_order }}</h4>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Create Shipment</button>
            </form>
            
            
        </div>
    </div>
</div>




{% endblock %}

templates/logistics/sales/dispatch_item_list.html
{% extends 'base.html' %}  
{% load custom_filters %} 
{% block content %}



<div class="container-fluid main-content">
    <div class="row">
        <h4>Dispatch Items for Sale Order: {{ sale_order.order_id }}</h4>
            <div class="col">              
                <div class="container fluid">
                    <div class="row">                        
                        <div class="col-12 col-md-4">
                            <table class="table table-hover">
                                <thead class="table-dark">
                                    <h5 style="color:green;font-weight: bolder;">Summary</h5>
                                    <tr>
                                        <th>#</th>
                                        <th>Product Name</th>
                                        <th>Order Quantity</th>
                                        <th>Dispatch Quantity</th>
                                        <th>Good Quantity</th>
                                        <th>Bad Quantity</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product_name, totals in product_wise_totals.items %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ product_name }}</td>
                                            <td>{{ totals.order_quantity }}</td>
                                            <td>{{ totals.dispatch_quantity }}</td>
                                            <td>{{ totals.good_quantity }}</td>
                                            <td>{{ totals.bad_quantity }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                                
                            </table>
                        </div>
                        <div class="col-12 col-md-4"></div>
                        <div class="col-12 col-md-4"></div>
                    </div>
                </div>
               
            </div>


        <div class="col mt-4">          

            {% for shipment, dispatch_items in shipments.items %}
                <h5>Sale Shipment ID: {{ shipment.shipment_id }} - Status: <span style="font-size: large;color:brown;font-weight: bold;">{{ shipment.get_status_display }}</span></h5>
            
                <table class="table table-hover">
                    <thead class="table-dark">
                      
                        <!-- Column headers -->
                        <tr>
                            <th rowspan="2" style="width: 5%;">#</th>
                            <th rowspan="2" style="width: 15%;">Item Name</th>
                            <th rowspan="2" style="color:yellow;font-weight: bold; width: 10%;">Order Qty</th>
                            <th rowspan="2" style="color:green;font-weight: bold; width: 10%;">Dispatch Qty</th>
                            <th rowspan="2" style="color:yellow;font-weight: bold; width: 15%;">Committed Delivery</th>
                            <th rowspan="2" style="color:green;font-weight: bold; width: 15%;">Actual Delivery</th>
                            <th rowspan="2" style="width: 10%;">Delivery Status</th>
                            <th rowspan="2" style="width: 20%;">Next Action</th>
                            <th rowspan="2" style="width: 10%;">Cancel</th>
                            <th colspan="2" style="color:yellow;font-weight: bold; width: 15%;">Quality Control</th>
                        </tr>
                        <!-- Sub-headers for Quality Control -->
                        <tr>
                            <th>Good Quantity</th>
                            <th>Bad Quantity</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        {% for shipment, dispatch_items in shipments.items %}
                            {% for dispatch_item in dispatch_items %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>

                                    <td>{{ dispatch_item.dispatch_item.product.name }}</td>                           
                                    <td>{{ dispatch_item.dispatch_item.quantity }}</td>
                                    <td>{{ dispatch_item.dispatch_quantity }}</td>
                                    <td>{{ dispatch_item.delivery_date }}</td>                                                           
                                    <td>
                                        {% if dispatch_item.status|item_list:"REACHED,OBI,DELIVERED" %}
                                            {{ dispatch_item.updated_at|date:"M-d,Y" }}
                                        {% else %}
                                            <span style="color:brown;font-weight: bold;">Not delivered yet</span>
                                        {% endif %}
                                    </td>

                                    
                                    <td>{{ dispatch_item.get_status_display }}</td>   
                                    <td>
                                        <form action="{% url 'logistics:update_sale_dispatch_status' dispatch_item.id %}" method="post">
                                            {% csrf_token %}
                                            <div class="d-flex align-items-center">
                                                <select name="new_status" class="form-select me-2" style="width: 60%;">
                                                    {% if dispatch_item.status == 'DISPATCHED' %}
                                                    <option value="IN_PROCESS">In Process</option>
                                                    {% elif dispatch_item.status == 'IN_PROCESS' %}
                                                        <option value="ON_BOARD">On Board</option>
                                                    {% elif dispatch_item.status == 'ON_BOARD' %}
                                                        <option value="IN_TRANSIT">In Transit</option>
                                                    {% elif dispatch_item.status == 'IN_TRANSIT' %}
                                                        <option value="CUSTOM_CLEARANCE_IN_PROCESS">Custom Clearance In Process</option>
                                                    {% elif dispatch_item.status == "CUSTOM_CLEARANCE_IN_PROCESS" %}
                                                        <option value="REACHED">Reached</option>   
                                                    {% elif dispatch_item.status == "OBI" %}
                                                        <option value="OBU">OBI</option>                                                                                                     
                                                   {% else %}
                                                        <option disabled selected>No action needed</option>
                                                    {% endif %}
                                                </select>
                                                <button type="submit" class="btn btn-secondary btn-sm">Update</button>
                                            </div> 
                                        </form>
                                    </td>
                                                                         
                                                               
                                <td>
                                    {% if dispatch_item.status|in_list:"REACHED,OBI,DELIVERED,ONBOARD,CUSTOM_CLEARANCE_IN_PROCESS"|yesno:"true,false" %}
                                    <i class="fas fa-times" style="color:red;font-weight: bold;"></i>
                                    {% else %}
                                    <a href="{% url 'logistics:cancel_sale_dispatch_item' dispatch_item.id %}" class="btn btn-sm btn-danger">Cancel</a>
                                    {% endif %}
                                </td>

                                    <td>
                                        {% if qc_quantities %}
                                        {{ qc_quantities|get_item:dispatch_item.id|get_item:'good_quantity'|default:0 }}
                                        {% endif %}
                                    </td>

                                    <td>   {% if qc_quantities %}
                                        {{ qc_quantities|get_item:dispatch_item.id|get_item:'bad_quantity'|default:0 }}
                                        {% endif %}
                                    </td>
                                    
                               
                            </tr>
                        {% endfor %}
                        {% endfor %}
                    </tbody>
                    
                </table>
            {% endfor %}
            
            </table>
        </div>
    </div>
</div>




{% endblock %}

templates/logistics/sales/shipment_details.html
{% extends "base.html" %}
{% load static %}

{% block content %}





<div class="container-fluid main-content">
    <div class="row">
        <div class="col-2"></div>
            <div class="col-12 col-md-8 mb-4">
                <div class="card shadow-lg" style="background-color: aliceblue;">
                    <!-- Card Header -->
                    <div class="card-header bg-primary text-white text-center">
                        <h4>Shipment Detail for {{ shipment.tracking_number }}</h4>
                    </div> 
                    <div class="card-body">                  
                                                                    
                        <table class="table table-hover table-dark">
                           
                            <tbody>
                                <tr>
                                    <th>Carrier</th>
                                    <td>{{ shipment.carrier }}</td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    <td>{{ shipment.get_status_display }}</td>
                                </tr>
                                <tr>
                                    <th>Estimated Delivery</th>
                                    <td>{{ shipment.estimated_delivery }}</td>
                                </tr>
                                <tr>
                                    <th>Created At</th>
                                    <td>{{ shipment.created_at }}</td>
                                </tr>
                                <tr>
                                    <th>Updated At</th>
                                    <td>{{ shipment.updated_at }}</td>
                                </tr>
                            </tbody>
                        </table>


                    </div>
                </div>           
            </div>
            <div class="col-2"></div>
            <div class="col-12">


                <h3>Tracking Updates</h3>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Update Time</th>
                            <th>Status Update</th>
                            <th>Remarks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for update in tracking_updates %}
                            <tr>
                                <td>{{ update.update_time }}</td>
                                <td>{{ update.status_update }}</td>
                                <td>{{ update.remarks }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="3">No tracking updates available.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'shipment:update_sale_shipment_tracking' shipment.id %}" class=" btn btn-primary btn-sm text-white">Update Shipment Tracking</a>
                
                
                
                <a href="{% url 'logistics:sale_shipment_list' %}" class="btn btn-sm btn-primary">Shipment List</a>
                              
                
            </div>

    </div>
    <h4 style="height:50px"></h4>
</div>







{% endblock %}