core/urls.py
from django.urls import path
from .import views


app_name = 'core'


urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.dashboard, name='dashboard'),
    path('core_dashboard/', views.core_dashboard, name='core_dashboard'),
    path('only_core_dashboard/', views.only_core_dashboard, name='only_core_dashboard'),
    path('view_employee/', views.view_employee, name='view_employee'),
    path('employee_list/', views.employee_list, name='employee_list'),
   
    path('manage_department/', views.manage_department, name='manage_department'),  
    path('manage_location/', views.manage_location, name='manage_location'),

    path('create_positionn/', views.manage_position, name='create_position'),    
    path('update_positionn/<int:id>/', views.manage_position, name='update_position'),    
    path('delete_position/<int:id>/', views.delete_position, name='delete_position'),  
    path('position_details/<int:id>/', views.position_details, name='position_details'),  

    path('create_job_requirement/', views.manage_job_requirement, name='create_job_requirement'),    
    path('update_job_requirement/<int:id>/', views.manage_job_requirement, name='update_job_requirement'),    
    path('delete_job_requirement/<int:id>/', views.delete_job_requirement, name='delete_job_requirement'),  

    path('create_job_description/', views.manage_job_description, name='create_job_description'),    
    path('update_job_description/<int:id>/', views.manage_job_description, name='update_job_description'),    
    path('delete_job_description/<int:id>/', views.delete_job_descriptiont, name='delete_job_description'),  

    path('create_company/', views.create_company, name='create_company'),
    path('update_company/<int:id>/', views.create_company, name='update_company'),
    path('delete_company/<int:id>/', views.delete_company,  name='delete_company'),    
    
    path('manage_employee/', views.manage_employee, name='manage_employee'),
    path('update_employee/<int:id>/', views.manage_employee, name='update_employee'),
    path('delete_employee/<int:id>/', views.delete_employee,  name='delete_employee'),    
            
    path('add_notice/', views.add_notice, name='add_notice'), 
    path('view_notices/', views.view_notices, name='view_notices'),  
    path('all_qc/', views.all_qc, name='all_qc'),

    path('view_attendance/', views.view_attendance, name='view_attendance'),
    path('attendance_input/', views.attendance_input, name='attendance_input'),
    path('update_attendance/<int:employee_id>/', views.update_attendance, name='update_attendance'),     
    
    path('create_salary/', views.create_salary, name='create_salary'),
    path('download_salary/', views.download_salary, name='download_salary'),

    path('view_employee_changes/', views.view_employee_changes, name='view_employee_changes'),
    path('download_employee_changes/', views.download_employee_changes, name='download_employee_changes'),

    path('view_employee_changes_single/<int:employee_id>/', views.view_employee_changes_single, name='view_employee_changes_single'),
    
    path('preview_pay_slip/<int:employee_id>/', views.preview_pay_slip, name='preview_pay_slip'),
    path('generate_and_send_pay_slip/<int:employee_id>/', views.generate_and_send_pay_slip, name='generate_and_send_pay_slip'),
        
    path('preview_salary_certificate/<int:employee_id>/', views.preview_salary_certificate, name='preview_salary_certificate'),
    path('generate_and_send_salary_certificate/<int:employee_id>/', views.generate_and_send_salary_certificate, name='generate_and_send_salary_certificate'),
          
    path('preview_experience_certificate/<int:employee_id>/', views.preview_experience_certificate, name='preview_experience_certificate'),
    path('generate_and_send_experience_certificate/<int:employee_id>/', views.generate_and_send_experience_certificate, name='generate_and_send_experience_certificate'),
      
    path('create_company_policy/', views.manage_company_policy, name='create_company_policy'),
    path('update_company_policy/<int:id>/', views.manage_company_policy, name='update_company_policy'),
    path('delete_company_policy/<int:id>/', views.delete_company_policy, name='delete_company_policy'),   

    path('create_salary_structure/', views.manage_salary_structure, name='create_salary_structure'),
    path('update_salary_structure/<int:id>/', views.manage_salary_structure, name='update_salary_structure'),
    path('delete_salary_structure/<int:id>/', views.delete_salary_structure, name='delete_salary_structure'),   
    
    path('create_festival/', views.manage_festival, name='create_festival'),
    path('update_festival/<int:id>/', views.manage_festival, name='update_festival'),
    path('delete_festival/<int:id>/', views.delete_festival, name='delete_festival'),   

    path('create_performance_bonus/', views.manage_performance_bonus, name='create_performance_bonus'),
    path('update_performance_bonus/<int:id>/', views.manage_performance_bonus, name='update_performance_bonus'),
    path('delete_performance_bonus/<int:id>/', views.delete_performance_bonus, name='delete_performance_bonus'),   

    path('create_leave_type/', views.manage_leave_type, name='create_leave_type'),
    path('update_leave_type/<int:id>/', views.manage_leave_type, name='update_leave_type'),
    path('delete_leave_type/<int:id>/', views.delete_leave_type, name='delete_leave_type'), 

    path('apply_leave/', views.apply_leave, name='apply_leave'),
    path('leave_history/', views.leave_history, name='leave_history'),
    path('pending_leave_list/', views.pending_leave_list, name='pending_leave_list'),
    path('approve_leave/<int:leave_id>/', views.approve_leave, name='approve_leave'),  
    path('leave_summary/', views.leave_summary, name='leave_summary'),
    path('leave_dashboard/', views.leave_dashboard, name='leave_dashboard'),

    path('carry-forward-leave/', views.carry_forward_leave, name='carry_forward_leave'),
    path('update_leave_balances_for_all/', views.monthly_leave_accrual_update, name='update_leave_balances_for_all'),
    path('check_and_deduct_late_leaves/', views.check_and_deduct_late_leaves, name='check_and_deduct_late_leaves'),

]

customer/urls.py
from django.urls import path
from .import views


app_name = 'customer'


urlpatterns = [ 
  

  path('create_customer/', views.create_customer, name='create_customer'),
  path('update_customer/<int:id>/', views.create_customer, name='update_customer'),
  path('delete_customer/<int:id>/', views.delete_customer,  name='delete_customer'),    
    
  
  path('create_location/', views.create_location, name='create_location'),
  path('update_location/<int:id>/', views.create_location, name='update_location'),
  path('delete_location/<int:id>/', views.delete_location, name='delete_location'),

  path('customer_performance_list/', views.customer_performance_list, name='customer_performance_list'),
  path('create_performance/', views.add_or_update_performance, name='create_performance'),
  path('update_performance/<int:performance_id>/', views.add_or_update_performance, name='update_performance'),
  
  path('customer_dashboard/', views.customer_dashboard, name='customer_dashboard'),
 
]

dscm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path("accounts/", include("django.contrib.auth.urls")), 

    path('core/',include('core.urls',namespace='core')),
    path('clients/',include('clients.urls',namespace='clients')),

    path('logistics/',include('logistics.urls',namespace='logistics')),
    path('manufacture/',include('manufacture.urls',namespace='manufacture')),
    path('product/',include('product.urls',namespace='product')),
    path('purchase/',include('purchase.urls',namespace='purchase')),
    path('sales/',include('sales.urls',namespace='sales')),
    path('supplier/',include('supplier.urls',namespace='supplier')),
    path('inventory/',include('inventory.urls',namespace='inventory')),
    path('finance/',include('finance.urls',namespace='finance')),
    path('shipment/',include('shipment.urls',namespace='shipment')),
    path('reporting/',include('reporting.urls',namespace='reporting')),
    path('customer/',include('customer.urls',namespace='customer')),
    path('repairreturn/',include('repairreturn.urls',namespace='repairreturn')),
    path('operations/',include('operations.urls',namespace='operations')),
    path('tasks/',include('tasks.urls',namespace='tasks')),
    path('commonapp/',include('commonapp.urls',namespace='commonapp')),
    path('transport/',include('transport.urls',namespace='transport')),
    path('customerportal/',include('customerportal.urls',namespace='customerportal')),
    path('recruitment/',include('recruitment.urls',namespace='recruitment')),
   
   
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/forms.py
from django import forms
from.models import Customer,Location
from .models import CustomerPerformance


class AddCustomerForm(forms.ModelForm):   
    class Meta:
        model = Customer
        exclude = ['customer_id','user']


class AddLocationForm(forms.ModelForm):
   
    address = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control custom-textarea',
                'rows': 3,  # Adjust the number of rows as needed
                'style': 'height: 30px;',  # Set the height directly if needed
            }
        )
    )
    class Meta:
        model=Location
        exclude = ['location_id','created_at','updated_at','user']



class UpdateLocationForm(forms.ModelForm):
    address = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control custom-textarea',
                'rows': 3, 
                'style': 'height: 30px;', 
            }
        )
    )
    class Meta:
        model=Location
        exclude = ['location_id','created_at','updated_at','user']





class CustomerPerformanceForm(forms.ModelForm):
    feedback = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control custom-textarea',
                'rows': 3,
                'style': 'height: 40px;', 
            }
        )
    )
    class Meta:
        model = CustomerPerformance
        exclude = ['user','created_at','updated_at','history']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),            
        }

customer/views.py
from django.shortcuts import render,redirect,get_object_or_404
from.forms import AddCustomerForm,AddLocationForm,UpdateLocationForm
from.models import Customer,Location
from django.core.paginator import Paginator
from django.contrib import messages

from .models import CustomerPerformance
from .forms import CustomerPerformanceForm 
from django.contrib.auth.decorators import login_required,permission_required




@login_required
def customer_dashboard(request):
    return render(request,'customer/customer_dashboard.html')



@login_required
def create_customer(request, id=None):  
    instance = get_object_or_404(Customer, id=id) if id else None
    message_text = "updated successfully!" if id else "added successfully!"  
    form = AddCustomerForm(request.POST or None, request.FILES or None, instance=instance)

    if request.method == 'POST' and form.is_valid():
        form_intance=form.save(commit=False)
        form_intance.save()        
        messages.success(request, message_text)
        return redirect('customer:create_customer')  

    datas = Customer.objects.all().order_by('-created_at')
    paginator = Paginator(datas, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'customer/create_customer.html', {
        'form': form,
        'instance': instance,
        'datas': datas,
        'page_obj': page_obj
    })


@login_required
def delete_customer(request, id):
    instance = get_object_or_404(Customer, id=id)
    if request.method == 'POST':
        instance.delete()
        messages.success(request, "Deleted successfully!")
        return redirect('customer:create_customer')  

    messages.warning(request, "Invalid delete request!")
    return redirect('customer:create_customer')  



@login_required
def create_location(request, id=None):  
    instance = get_object_or_404(Location, id=id) if id else None
    message_text = "updated successfully!" if id else "added successfully!"  
    form = AddLocationForm(request.POST or None, request.FILES or None, instance=instance)

    if request.method == 'POST' and form.is_valid():
        form_intance=form.save(commit=False)
        form_intance.save()        
        messages.success(request, message_text)
        return redirect('customer:create_location')  

    datas = Location.objects.all().order_by('-created_at')
    paginator = Paginator(datas, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'customer/create_location.html', {
        'form': form,
        'instance': instance,
        'datas': datas,
        'page_obj': page_obj
    })


@login_required
def delete_location(request, id):
    instance = get_object_or_404(Location, id=id)
    if request.method == 'POST':
        instance.delete()
        messages.success(request, "Deleted successfully!")
        return redirect('customer:create_location')   

    messages.warning(request, "Invalid delete request!")
    return redirect('customer:create_location')  



@login_required
def customer_performance_list(request):
    performances = CustomerPerformance.objects.all().order_by('-created_at')
    paginator = Paginator(performances, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'customer/customer_performance_list.html', {'page_obj': page_obj})


@login_required
def add_or_update_performance(request, performance_id=None):
    if performance_id:
        performance = get_object_or_404(CustomerPerformance, id=performance_id)
        message_text = "Customer performance updated successfully!"
    else:
        performance = None
        message_text = "Customer performance added successfully!"
        
    form = CustomerPerformanceForm(request.POST or None, instance=performance)

    if request.method == 'POST':
        if form.is_valid():
            form_instance=form.save(commit=False)
            form_instance.user=request.user
            form_instance.save()
            messages.success(request, message_text)
            return redirect('customer:customer_performance_list')

    return render(request, 'customer/create_or_update_performance.html', {'form': form, 'performance': performance})

templates/customer/confirm_delete.html
{% extends 'base.html' %}  

{% block content %}



<div class="container-fluid main-content">
    <div class="row"> 
        <div class="col-12 col-md-2"></div>
            <div class="col-12 col-md-8">
                <h4 class="text-center">Are you sure you want to delete customer location:<span style="color:red"> {{ location.name }}?</span></h4>       
                <div class="card shadow-lg" style="padding:10px;background-color:azure;">
                    <div class="card-body">
                        <h2>Confirm Deletion</h2>
                            <p>Are you sure you want to delete the location: {{ location.name }}?</p>

                            <form method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Confirm Delete</button>
                            </form>

                            <a href="{% url 'customer:create_location' %}" class="btn btn-secondary">Cancel</a>

                     </div>
                </div>           
            </div>
            <div class="col-12 col-md-2"></div>
    </div>
</div>


 {% endblock %}

templates/customer/create_customer.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="container-fluid main-content">
    <div class="row">
        <div class="col-12 col-md-4">
            <div class="card shadow-lg" style="background-color: aliceblue;">
                 <!-- Card Header -->
                 <div class="card-header bg-primary text-white text-center">
                    <h3 class="mb-0"> {% if instance %} Update {% else %} Create {% endif %}</h3>
                </div>              
                <form method="POST" enctype="multipart/form-data" class="p-2 m-4">
                    {% csrf_token %}
                    {{ form.as_p }}   
                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary btn-lg"> {% if instance %} Update {% else %} Add {% endif %}</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-12 col-md-8">
            <table class="table table-hover">
                <thead class="table-dark">
                    <tr>
                        <th class="text-center p-2">Name</th>
                        <th class="text-center p-2">logo</th>
                        <th class="text-center p-2">Contac Person</th>  
                        <th class="text-center p-2">Email</th>    
                        <th class="text-center p-2">Phone</th>      
                        <th class="text-center p-2">Website</th>               
                        <th class="text-center p-2">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in page_obj %}
                        <tr>
                            <td class="text-center p-1">{{ data.name }}</td>
                            <td>
                                {% if data.logo%}
                                <img src="{{ data.logo.url }}" class="card-img-top rounded-circle" alt="{{ data.name }}" style="width:30px;height:30px;">
                                {% endif %}
                            </td>
                            <td class="text-center p-1">{{ data.contact_person}}</td>                            
                            <td class="text-center p-2" style="white-space: nowrap;">{{data.email}}</td>
                            <td class="text-center p-2" style="white-space: nowrap;">{{data.phone}}</td>
                            <td class="text-center p-2" style="white-space: nowrap;">{{data.website}}</td>
                           
                           
                            <td class="text-center">
                                <a href="{% url 'customer:create_customer' %}" class="btn btn-sm btn-info">Add</a>
                                <a href="{% url 'customer:update_customer' data.id %}" class="btn btn-sm btn-info">Edit</a>
                               
                                <a href="#" 
                                    class="btn btn-danger btn-sm" 
                                    data-bs-toggle="modal" 
                                    data-bs-target="#deleteModal" 
                                    data-id="{{ data.id }}" 
                                    data-name="{{ data.name }}">
                                        Delete
                                    </a>
                               
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="5" class="text-center">No records available.</td>
                        </tr>
                    {% endfor %}
                </tbody>
                
            </table>
                    
            <!-- Pagination Controls -->
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>


             <!-- Delete Confirmation Modal -->
             <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete the transport record: <strong id="modal-entity-name"></strong>?
                        </div>
                        <div class="modal-footer">
                            <form method="post" id="delete-form">
                                {% csrf_token %}
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-danger">Yes, Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
</div>



<script>
    const deleteModal = document.getElementById('deleteModal');
    deleteModal.addEventListener('show.bs.modal', function (event) {
        const button = event.relatedTarget; 
        const entityId = button.getAttribute('data-id');
        const entityName = button.getAttribute('data-name');

          const modalEntityName = deleteModal.querySelector('#modal-entity-name');
        modalEntityName.textContent = entityName;
  
        const deleteForm = deleteModal.querySelector('#delete-form');
        deleteForm.action = `/customer/delete_customer/${entityId}/`;
    });
</script>




{% endblock %}

templates/customer/create_or_update_performance.html
{% extends "base.html" %}

{% block content %}


 

  <div class="conatiner-fluid">
    <div class="row">
      <div class="col-12 col-md-3"></div>
      <div class="col-12 col-md-6">
        <div class="card shadow" style="background-color: aliceblue;">
           <!-- Card Header -->
           <div class="card-header bg-primary text-white text-center">
            <h3 class="mb-0">{% if performance %}Update{% else %}Add{% endif %} Customer Performances</h3>
        </div> 
          <div class="card-body">    
            
            <form method="post" class="m-4">
              {% csrf_token %}
              {{ form.as_p }}
              <div class="d-grid">
              <button type="submit" class="btn btn-success btn-lg">{% if performance %}Update{% else %}Add{% endif %} Performance</button>
            </div>
              <a href="{% url 'customer:customer_performance_list' %}" class="btn btn-danger mt-4">Cancel</a>
            </form>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-3"></div>
    </div>
  </div>
  


{% endblock %}

templates/customer/customer_dashboard.html
    {% extends 'base.html' %}  

    {% block content %}
   
    
    <div class="container-fluid main-content">
        <div class="row">       
           
            <div class="col-6 col-md-3 col-lg-2 p-2">
                <a href="{% url 'customer:create_customer' %}" class="text-decoration-none">
                    <div class="menu-card">
                        <i class="fas fa-plus-square menu-icon"></i>
                        <div class="menu-title">Create Customer</div>
                    </div>
                </a>
            </div>
            <div class="col-6 col-md-3 col-lg-2 p-2">
                <a href="{% url 'customer:create_location' %}"class="text-decoration-none">
                    <div class="menu-card">
                        <i class="fas fa-plus-square menu-icon"></i>
                        <div class="menu-title">Create Location</div>
                    </div>
                </a>
            </div>      
    
            <div class="col-6 col-md-3 col-lg-2 p-2">
                <a href="{% url 'customer:customer_performance_list' %}"  class="text-decoration-none">
                    <div class="menu-card">
                        <i class="fas fa-solid fas fa-chart-line menu-icon"></i>
                        <div class="menu-title">Customer Performance</div>
                    </div>
                </a>
            </div>       
        </div>
    </div>
    
 
    
    
    {% endblock %}

templates/customer/customer_performance_list.html
{% extends "base.html" %}

{% block content %}
  <h2>Customer Performance List</h2>

  <table class="bg-light">
    <thead class="bg-dark text-white">
      <tr> 
        <th>Customer</th>
        <th>Customer</th>
        <th>Location</th>
        <th>Date</th>
        <th>Delivery Rating</th>
        <th>Quality Rating</th>
        <th>On Time Delivery</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for performance in page_obj %}
        <tr>
          <td>{{ performance.customer }}</td>
          <td>{{ performance.location }}</td>
          <td>{{ performance.date }}</td>
          <td>{{ performance.delivery_rating }}</td>
          <td>{{ performance.quality_rating }}</td>
          <td>{{ performance.on_time_delivery|yesno:"Yes,No" }}</td>
          <td>
            <a href="{% url 'customer:update_performance' performance.id %}" class="btn btn-warning btn-sm">Edit</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="pagination">
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-secondary">Previous</a>
    {% endif %}
    
    <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
    
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class="btn btn-secondary">Next</a>
    {% endif %}
  </div>

  <a href="{% url 'customer:create_performance' %}" class="btn btn-primary mt-3">Add New Performance</a>
{% endblock %}

templates/customer/update_location.html
{% extends 'base.html' %}  

{% block content %}


<div class="container-fluid main-content">
    <div class="row">   
                 <!-- Form for adding a new category -->
            <div class="col-12 col-md-4">
                <div class="card shadow" style="padding:10px;background-color:aquamarine;">
                    <div class="card-body">
                        <h6 class="card-title text-center"><strong>Update Location</strong> </h6>
                        <form method="post" enctype="multipart/form-data" action="" id="add_category">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" name="location_submit" class="btn btn-primary">Submit</button>
                        </form>
                     </div>
                </div>           
            </div>

            <div class="col">        
                <!-- Table for displaying existing categories -->
                <h4>Available Locations</h4>
                <table class="table table-hover">
                    <thead class="table-dark">
                        <tr>
                            <th class="text-center p-2">Name</th>
                            <th class="text-center p-2">Customer</th>
                            <th class="text-center p-2">Address</th>
                            <th class="text-center p-2">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for location in page_obj%}
                            <tr>
                                <td class="text-center p-1">{{ location.name }}</td>
                                <td class="text-center p-1" style="white-space: nowrap;">{{ location.customer.name }}</td>
                                <td class="text-center p-2" style="white-space: nowrap;">{{location.address }}</td>    
                                <td class="text-center">                                   
                                        <!-- Update Button Form -->
                                        <a href="{% url 'customer:create_location'%}" class="btn btn-primary btn-sm text-center">Add</a>
                                        <a href="{% url 'customer:update_location' location.id %}" class="btn btn-primary btn-sm text-center">Update</a>
                                    
                                        <!-- Delete Button that links to confirmation page -->
                                        <a href="{% url 'customer:delete_location' location.id %}" class="btn btn-danger btn-sm text-center">Delete</a>
                                    </td>
                               
                                
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                             <!-- Pagination Controls -->
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
            </div>
        
    </div>
</div>      



{% endblock %}