accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import logged_out_view  
from clients.views import tenant_expire_check


from django.views.generic import TemplateView
from.forms import PwdResetConfirmForm,PwdResetForm



app_name = 'accounts'

urlpatterns = [
    path('', tenant_expire_check, name='tenant_expire_check'),
    path('home/', views.home, name='home'),

    path('login/', views.login_view, name='login'),
    path('login_public/', views.login_public, name='login_public'),   
    path('login_partner_job_seeker/', views.login_partner_job_seeker, name='login_partner_job_seeker'),
    
    #path('logout/', auth_views.LogoutView.as_view(next_page='accounts:logged_out'), name='logout'),
    path('logout/', views.logged_out_view, name='logout'),
 
   
   ###################################################################################################
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_reset/password_change.html',
            success_url='/password_change/done/'), name='password_change' ),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_reset/password_change_done.html', ),
          name='password_change_done'),
    ################################################################################

      # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="accounts/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
          ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
         ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="accounts/password_reset/reset_status.html"),
        name="password_reset_done",
          ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="accounts/password_reset/reset_status.html"),
        name="password_reset_complete",
          ),

   ####################################################################################################
  
   # Custom views
    path('register/', views.register_view, name='register'), 
    path('register_partner_job_seeker/', views.register_partner_job_seeker, name='register_partner_job_seeker'),
    # path('register_job_seeker/', views.register_job_seeker, name='register_job_seeker'), 
    path('register_public/', views.register_public, name='register_public'),   
    path("activate/<slug:uidb64>/<slug:token>)/", views.account_activate, name="activate"),
  
    path('update_profile_picture/', views.update_profile_picture, name='update_profile_picture'),
    path('common_search/', views.common_search, name='common_search'),

    ###################################################################################################
  # Permission
  path('assign_permissions/', views.assign_permissions, name='assign_permissions'),
  path('assign_user_to_group/', views.assign_user_to_group, name='assign_user_to_group'),
  path('assign_permissions_to_group/', views.assign_permissions_to_group, name='assign_permissions_to_group'),
  path('get_permissions_for_model/', views.get_permissions_for_model, name='get_permissions_for_model'),
  path('search_all/', views.search_all, name='search_all')
  

]

core/urls.py
from django.urls import path
from .import views


app_name = 'core'


urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.dashboard, name='dashboard'),
    path('core_dashboard/', views.core_dashboard, name='core_dashboard'),
    path('only_core_dashboard/', views.only_core_dashboard, name='only_core_dashboard'),
    path('view_employee/', views.view_employee, name='view_employee'),
    path('employee_list/', views.employee_list, name='employee_list'),
   
    path('manage_department/', views.manage_department, name='manage_department'),  
    path('manage_location/', views.manage_location, name='manage_location'),

    path('create_positionn/', views.manage_position, name='create_position'),    
    path('update_positionn/<int:id>/', views.manage_position, name='update_position'),    
    path('delete_position/<int:id>/', views.delete_position, name='delete_position'),  
    path('position_details/<int:id>/', views.position_details, name='position_details'),  

    path('create_job_requirement/', views.manage_job_requirement, name='create_job_requirement'),    
    path('update_job_requirement/<int:id>/', views.manage_job_requirement, name='update_job_requirement'),    
    path('delete_job_requirement/<int:id>/', views.delete_job_requirement, name='delete_job_requirement'),  

    path('create_job_description/', views.manage_job_description, name='create_job_description'),    
    path('update_job_description/<int:id>/', views.manage_job_description, name='update_job_description'),    
    path('delete_job_description/<int:id>/', views.delete_job_descriptiont, name='delete_job_description'),  

    path('create_company/', views.create_company, name='create_company'),
    path('update_company/<int:id>/', views.create_company, name='update_company'),
    path('delete_company/<int:id>/', views.delete_company,  name='delete_company'),    
    
    path('manage_employee/', views.manage_employee, name='manage_employee'),
    path('update_employee/<int:id>/', views.manage_employee, name='update_employee'),
    path('delete_employee/<int:id>/', views.delete_employee,  name='delete_employee'),    
            
    path('add_notice/', views.add_notice, name='add_notice'), 
    path('view_notices/', views.view_notices, name='view_notices'),  
    path('all_qc/', views.all_qc, name='all_qc'),

    path('view_attendance/', views.view_attendance, name='view_attendance'),
    path('attendance_input/', views.attendance_input, name='attendance_input'),
    path('update_attendance/<int:employee_id>/', views.update_attendance, name='update_attendance'),     
    
    path('create_salary/', views.create_salary, name='create_salary'),
    path('download_salary/', views.download_salary, name='download_salary'),

    path('view_employee_changes/', views.view_employee_changes, name='view_employee_changes'),
    path('download_employee_changes/', views.download_employee_changes, name='download_employee_changes'),

    path('view_employee_changes_single/<int:employee_id>/', views.view_employee_changes_single, name='view_employee_changes_single'),
    
    path('preview_pay_slip/<int:employee_id>/', views.preview_pay_slip, name='preview_pay_slip'),
    path('generate_and_send_pay_slip/<int:employee_id>/', views.generate_and_send_pay_slip, name='generate_and_send_pay_slip'),
        
    path('preview_salary_certificate/<int:employee_id>/', views.preview_salary_certificate, name='preview_salary_certificate'),
    path('generate_and_send_salary_certificate/<int:employee_id>/', views.generate_and_send_salary_certificate, name='generate_and_send_salary_certificate'),
          
    path('preview_experience_certificate/<int:employee_id>/', views.preview_experience_certificate, name='preview_experience_certificate'),
    path('generate_and_send_experience_certificate/<int:employee_id>/', views.generate_and_send_experience_certificate, name='generate_and_send_experience_certificate'),
      
    path('create_company_policy/', views.manage_company_policy, name='create_company_policy'),
    path('update_company_policy/<int:id>/', views.manage_company_policy, name='update_company_policy'),
    path('delete_company_policy/<int:id>/', views.delete_company_policy, name='delete_company_policy'),   

    path('create_salary_structure/', views.manage_salary_structure, name='create_salary_structure'),
    path('update_salary_structure/<int:id>/', views.manage_salary_structure, name='update_salary_structure'),
    path('delete_salary_structure/<int:id>/', views.delete_salary_structure, name='delete_salary_structure'),   
    
    path('create_festival/', views.manage_festival, name='create_festival'),
    path('update_festival/<int:id>/', views.manage_festival, name='update_festival'),
    path('delete_festival/<int:id>/', views.delete_festival, name='delete_festival'),   

    path('create_performance_bonus/', views.manage_performance_bonus, name='create_performance_bonus'),
    path('update_performance_bonus/<int:id>/', views.manage_performance_bonus, name='update_performance_bonus'),
    path('delete_performance_bonus/<int:id>/', views.delete_performance_bonus, name='delete_performance_bonus'),   

    path('create_leave_type/', views.manage_leave_type, name='create_leave_type'),
    path('update_leave_type/<int:id>/', views.manage_leave_type, name='update_leave_type'),
    path('delete_leave_type/<int:id>/', views.delete_leave_type, name='delete_leave_type'), 

    path('apply_leave/', views.apply_leave, name='apply_leave'),
    path('leave_history/', views.leave_history, name='leave_history'),
    path('pending_leave_list/', views.pending_leave_list, name='pending_leave_list'),
    path('approve_leave/<int:leave_id>/', views.approve_leave, name='approve_leave'),  
    path('leave_summary/', views.leave_summary, name='leave_summary'),
    path('leave_dashboard/', views.leave_dashboard, name='leave_dashboard'),

    path('carry-forward-leave/', views.carry_forward_leave, name='carry_forward_leave'),
    path('update_leave_balances_for_all/', views.monthly_leave_accrual_update, name='update_leave_balances_for_all'),
    path('check_and_deduct_late_leaves/', views.check_and_deduct_late_leaves, name='check_and_deduct_late_leaves'),

]

dscm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path("accounts/", include("django.contrib.auth.urls")), 

    path('core/',include('core.urls',namespace='core')),
    path('clients/',include('clients.urls',namespace='clients')),

    path('logistics/',include('logistics.urls',namespace='logistics')),
    path('manufacture/',include('manufacture.urls',namespace='manufacture')),
    path('product/',include('product.urls',namespace='product')),
    path('purchase/',include('purchase.urls',namespace='purchase')),
    path('sales/',include('sales.urls',namespace='sales')),
    path('supplier/',include('supplier.urls',namespace='supplier')),
    path('inventory/',include('inventory.urls',namespace='inventory')),
    path('finance/',include('finance.urls',namespace='finance')),
    path('shipment/',include('shipment.urls',namespace='shipment')),
    path('reporting/',include('reporting.urls',namespace='reporting')),
    path('customer/',include('customer.urls',namespace='customer')),
    path('repairreturn/',include('repairreturn.urls',namespace='repairreturn')),
    path('operations/',include('operations.urls',namespace='operations')),
    path('tasks/',include('tasks.urls',namespace='tasks')),
    path('commonapp/',include('commonapp.urls',namespace='commonapp')),
    path('transport/',include('transport.urls',namespace='transport')),
    path('customerportal/',include('customerportal.urls',namespace='customerportal')),
    path('recruitment/',include('recruitment.urls',namespace='recruitment')),
   
   
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transport/urls.py
from django.urls import path
from .import views


app_name = 'transport'


urlpatterns = [
    path('transport_dashboard/', views.transport_dashboard, name='transport_dashboard'),
    path('create_transport/', views.manage_transport, name='create_transport'),
    path('update_transport/<int:id>/', views.manage_transport, name='update_transport'),
    path('delete_transport/<int:id>/', views.delete_transport, name='delete_transport'),
   
    path('transport_details/<int:transport_id>/', views.transport_details, name='transport_details'),
    path('available_transports/', views.available_transports, name='available_transports'),  # View available transport
   
    path('create_transport_request/', views.create_transport_request, name='create_transport_request'),
    path('update_transport_request/<int:id>/', views.create_transport_request, name='update_transport_request'),  # Request transport
    path('delete_transport_request/<int:id>/', views.delete_transport_request, name='delete_transport_request'),  # Request transport
    path('create_transport_request_id/<int:id>/', views.create_transport_request_id, name='create_transport_request_id'),  # Request transport    
   
   
    path('request/<int:request_id>/approve/', views.transport_request_approval, name='transport_request_approval'),  # Approve request (manager)
    path('update_booking/<int:booking_id>/', views.update_booking, name='update_booking'),  # Approve request (manager)
   
    path('booking_history/', views.booking_history, name='booking_history'),  
    
    path('create_time_extension/<int:id>/', views.create_time_extension, name='create_time_extension'),    
    path('approve_time_extension/<int:id>/', views.approve_time_extension, name='approve_time_extension'), 


    path('transport_usage_update/<int:booking_id>/', views.transport_usage_update, name='transport_usage_update'),  
    path('penalty_history/', views.penalty_history, name='penalty_history'),
   
    path('create_fuel_refill/', views.manage_fuel_refill, name='create_fuel_refill'),  
    path('update_fuel_refill/<int:id>/', views.manage_fuel_refill, name='update_fuel_refill'),  
  
    path('create_vehicle_fault/', views.create_vehicle_fault, name='create_vehicle_fault'),   
    path('update_vehicle_fault/<int:id>/', views.create_vehicle_fault, name='update_vehicle_fault'),

    path('create_fuel_pump_database/', views.manage_fuel_pump, name='create_fuel_pump_database'),
    path('update_fuel_pump_database/<int:id>/', views.manage_fuel_pump, name='update_fuel_pump_database'),
    path('delete_fuel_pump/<int:id>/', views.delete_fuel_pump, name='delete_fuel_pump'), 
        
    
    path('create_vehicle_payment/', views.create_vehicle_payment, name='create_vehicle_payment'),
    path('update_vehicle_payment/<int:id>/', views.create_vehicle_payment, name='update_vehicle_payment'),
    path('delete_vehicle_payment/<int:id>/', views.delete_vehicle_payment, name='delete_vehicle_payment'),

    path('create_fuel_pump_payment/', views.create_fuel_pump_payment, name='create_fuel_pump_payment'),  
    path('update_fuel_pump_payment/<int:id>/', views.create_fuel_pump_payment, name='update_fuel_pump_payment'), 
    path('delete_fuel_pump_payment/<int:id>', views.delete_fuel_pump_payment, name='delete_fuel_pump_payment'), 
  
    path('fuel_by_pump/', views.fuel_by_pump, name='fuel_by_pump'),   
    path('datewise_fuel_withdraw/', views.datewise_fuel_withdraw, name='datewise_fuel_withdraw'),  
   
    path('vehicle_overtime_calc/', views.vehicle_overtime_calc, name='vehicle_overtime_calc'),
    path('vehicle_grand_summary/', views.vehicle_grand_summary, name='vehicle_grand_summary'),
    path('management_summary_report/', views. management_summary_report, name='management_summary_report'),
  
    path('refresh-status/', views.refresh_status, name='refresh_status'),

    path('vehicle_booking_calendar/<int:id>/', views.vehicle_booking_calendar, name='vehicle_booking_calendar'),
    path('penalty_payment/<int:penalty_id>/', views.penalty_payment, name='penalty_payment'),

   ]

templates/fleetmanagement/create_transport_request_id.html
{% extends "base.html" %}

{% block content %}
     

<div class="container-fluid main-content">
    <div class="row">
        <div class="col-12">
            <form method="get" class="mb-4">
                <div class="row">
                    <div class="col-md-3">
                        <label for="start_date">Start Date:</label>
                        <input type="date" id="start_date" name="start_date" class="form-control" value="{{ start_date|date:'Y-m-d' }}">
                    </div>
                    <div class="col-md-3">
                        <label for="end_date">End Date:</label>
                        <input type="date" id="end_date" name="end_date" class="form-control" value="{{ end_date|date:'Y-m-d' }}">
                    </div>
                    <div class="col-md-3">
                        <label for="end_date">Vehicle Reg number:</label>
                        <input type="text" id="vehicle_number" name="vehicle_number" class="form-control" value="{{ vehicle_number }}">
                    </div>
                    <div class="col-md-3 d-flex align-items-end">
                        <button type="submit" class="btn btn-primary">Filter</button>
                    </div>
                </div>
            </form>
            
        </div>
        <div class="col-4 mb-4">
            <div class="card shadow-lg" style="background-color: aliceblue;">
                <!-- Card Header -->
                <div class="card-header bg-primary text-white text-center">
                    <h3 class="mb-0">Create Transport Request</h3>
                </div> 
                <div class="card shadow-sm mb-4">                   
                    <div class="card-body">
                        {% if instance.status != 'AVAILABLE' %}
                            <div class="alert alert-info">
                                <strong>This Vehicle is recently Scheduled as:</strong>
                                <ul class="list-unstyled mb-0">
                                    <li><strong>From:</strong> {{ instance.transport_request.first.request_datetime|date:"Y-m-d H:i" }}</li>
                                    <li><strong>To:</strong> {{ instance.transport_request.first.return_datetime|date:"Y-m-d H:i" }}</li>
                                    <li><strong>Booked By:</strong> {{ instance.transport_request.first.staff }}</li>
                                </ul>
                            </div>
                        {% else %}
                            <div class="alert alert-warning">
                                <strong>No current booking for this vehicle.</strong>
                            </div>
                        {% endif %}
                
                        <form method="post" enctype="multipart/form-data" action="" id="add_transport_request">
                            {% csrf_token %}
                            {{ form.as_p }}
                           
                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary btn-lg">
                                    Submit Request
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
                
        </div>
    </div>
    <div class="col-8 table-responsive">
        <h2>Requisition List</h2>
        
        {% if page_obj %}
          
        <table class="table table-hover">
            <thead class="table-dark">
                    <tr>
                        <th>Actions</th>
                        <th class="text-center p-2">Requisition Approval</th>
                        <th class="text-center p-2">Time extension </th>
                        <th class="text-center p-2">Usage Log </th>    
                        <th class="text-center p-2">Update booking </th>  
                        <th class="text-center p-2">Status</th>                   
                        <th class="text-center p-2">Vehicle code</th>
                        <th class="text-center p-2">Vehicle Reg Number</th>
                        <th class="text-center p-2">Vehicle Ownership</th>
                        <th class="text-center p-2">Mileage</th>
                        <th class="text-center p-2">Requester</th>      
                        <th class="text-center p-2">Requisition Date</th>                     
                        <th class="text-center p-2">Return date</th>
                        <th class="text-center p-2">Purpose</th>
                        <th class="text-center p-2">Created</th>
                        <th class="text-center p-2">Updated</th>
                    
                      
                    </tr>
                </thead>
                <tbody>
                    {% for data in page_obj %} 
                        <tr>
                                                           
                                    <td class="text-center">                                       
                                        <a href="{% url 'transport:update_transport_request' data.id %}" class="btn btn-sm btn-info">Edit</a>
                                        <a href="#" 
                                            class="btn btn-danger btn-sm" 
                                            data-bs-toggle="modal" 
                                            data-bs-target="#deleteModal" 
                                            data-id="{{ data.id }}" 
                                            data-name="{{ data.fuel_pump_name }}">
                                                Delete
                                            </a>
                                    </td>

                                    <td class="text-center p-1">
                                        {% if data.request_approval.first.status == 'APPROVED' %}
                                        <i class="fas fa-check text-success">Approved</i>
                                        {% elif data.request_approval.first.status == 'REJECTED' %}
                                        <i class="fas fa-check text-warning">Rejected</i>
                                        {% else %}
                                        <a href="{% url 'transport:transport_request_approval' data.id %}"><i class="fas fa-times text-danger fw-bold">Pending Approval</i></a>
                                        {% endif %}
                                    </td> 


                                 <td>                                
                                {% if data.status == 'COMPLETED' %}
                                <i class="fas fa-check fw-bold text-success"></i>
                                {% elif data.time_extension.first.approval_status == 'PENDING' %}
                                <a href="{% url 'transport:create_time_extension' data.id %}">
                                    <i class="fas fa-times text-danger fw-bold">Approval pending</i>
                                </a>
                                {% else %}
                                <a href="{% url 'transport:create_time_extension' data.id %}"><i class="fas fa-plus-circle"></i>Time extension</a>
                                {% endif %}
                            </td>
                            
                            <td>                              
                                <a href="{% url 'transport:transport_usage_update' data.id %}">Log data</a>                               
                            </td>

                            <td>
                                {% if data.status == 'COMPLETED' %}
                                <i class="fas fa-check fw-bold text-success"></i>
                                {% else %}
                                <a href="{% url 'transport:update_booking' data.id %}">Update Booking</a>
                                {% endif %}
                            </td>
                            <td class="text-center p-1">
                                {% if data.status == 'IN-USE' %}
                                <i class="fas fa-truck text-primary">&nbsp;{{ data.get_status_display}}</i>
                                {% elif data.status == 'PENALIZED' %}
                                <i class="fas fa-truck text-danger">&nbsp;{{ data.get_status_display}}</i>
                                {% elif data.status == 'BOOKED' %}
                                <i class="fas fa-check text-success">&nbsp;{{ data.get_status_display}}</i>
                                {% elif data.status == 'COMPLETED'%}
                                <i class="fas fa-check text-primary">&nbsp;{{ data.get_status_display}}</i>
                                {% else %}
                                <i class="fas fa-times text-warning">&nbsp;{{ data.get_status_display}}</i>
                                {% endif %}
                            </td> 
                            <td class="text-center p-1">{{ data.vehicle.vehicle_code }}</td>
                            <td class="text-center p-1">{{ data.vehicle.vehicle_registration_number }}</td>  
                            <td class="text-center p-1">{{ data.vehicle.get_vehicle_ownership_display }}</td>  
                            <td class="text-center p-1">{{ data.vehicle.vehicle_mileage}}</td>    
                            <td class="text-center p-1">{{ data.staff.username}}</td>
                            <td class="text-center p-1">{{ data.request_datetime}}</td>   
                            <td class="text-center p-1">{{ data.return_datetime}}</td>   
                            <td class="text-center p-1">{{ data.purpose}}</td>                      
                            <td class="text-center p-2" style="white-space: nowrap;">{{data.created_at}}</td>
                            <td class="text-center p-2" style="white-space: nowrap;">{{data.updated_at}}</td>
                            
                            
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="5" class="text-center">No locations available.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
                        
                <!-- Pagination Controls -->
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>

            {% endif %}
    </div>

</div>
</div>



            <!-- Delete Confirmation Modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete the transport record: <strong id="modal-vehicle-name"></strong>?
                        </div>
                        <div class="modal-footer">
                            <form method="post" id="delete-form">
                                {% csrf_token %}
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-danger">Yes, Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


            
<script>
    const deleteModal = document.getElementById('deleteModal');
    deleteModal.addEventListener('show.bs.modal', function (event) {
        const button = event.relatedTarget; // Button that triggered the modal
        const transportId = button.getAttribute('data-id');
        const transportName = button.getAttribute('data-name');

        // Update the modal content
        const modalVehicleName = deleteModal.querySelector('#modal-vehicle-name');
        modalVehicleName.textContent = transportName;

        // Update the form action
        const deleteForm = deleteModal.querySelector('#delete-form');
        deleteForm.action = `/transport/delete_transport_request/${transportId}/`;
    });
</script>







<script>
    $(document).ready(function () {
     function toggleFields() {
         var entityType = $('#id_transport_type').val();
 
         if (entityType === 'Goods') {
             $('#id_item_description').closest('p').show();                
         } else if (entityType === 'Staff') {
             $('#id_item_description').closest('p').hide();
         }
     }
 
     toggleFields(); // Initial call
     $('#id_transport_type').change(function () {
         toggleFields(); // Update fields on change
     });
 });
 
 </script>
 
{% endblock %}